### ISSUE TITLE
Heads up, there at NSFW words in here :0

### ISSUE THREAD

**Issue by ardeay** [cirello-io/goherokuname#1]

**Comment by ucirello** [comment]
I am going to check into that.

**Comment by ucirello** [comment]
Fixed by: https://github.com/cirello-io/public/commit/644a95d82e17d1edc33401ef2b56632f1a21bf38

**Comment by ardeay** [comment]
Bummer you deleted the package. That wasn't my intent. I was simply warning
folks because we almost used it in production before we caught some very
adult words.

**Comment by ucirello** [comment]
@ardeay you can always resort to a previous version in which the words were there. I preferred to err on the side of caution. I am sorry.
